Remove unused optional dep to avoid circular dep
mt-mods/moretrees pull request #21
Opened 2022-12-03 19:36 UTC by Awkanimus

Removing `ethereal` from the `optional_depends` because it is not used in moretrees and it creates a circular dependency.

The dependency cycle this solves is currently ethereal --> bakedclay --> flowerpot --> moretrees --> ethereal.

2022-12-03 19:43 UTC, Niklp09 commented
https://github.com/mt-mods/moretrees/pull/11#discussion_r1002973356

Was this fixed by TenPlus1?

2022-12-03 19:44 UTC, wsor4035 commented
> [#11 (comment)](https://github.com/mt-mods/moretrees/pull/11#discussion_r1002973356)
> 
> Was this fixed by TenPlus1?

nope

2022-12-03 19:46 UTC, wsor4035 commented
to clarify the label, tenplus1 is to blame here for still nuking things unless mods dep on ethereal to load after it

2022-12-03 19:47 UTC, Niklp09 commented
relevant yl issue https://gitea.your-land.de/your-land/bugtracker/issues/3013

2022-12-03 19:51 UTC, wsor4035 commented
~~probably~~ should make an issue from tracking the status so we dont forget
^ ill do this

2022-12-03 19:54 UTC, wsor4035 commented
see https://github.com/mt-mods/moretrees/issues/22

2022-12-08 13:18 UTC, Awkanimus commented
Forgot to comment. Thanks for the clarification. I'll watch the related bug.

2022-12-10 20:02 UTC, wsor4035 requested changes
see https://github.com/mt-mods/moretrees/issues/22#issuecomment-1345134188 - mine and buckaroos comments

2022-12-11 07:11 UTC, Awkanimus commented
Updated as requested. Notes:
1. Made generic so the same mod_dependency_checks.lua could be used in other projects
2. Dependencies can be marked as "fatal" in which case server does not start when check fails
3. Dependencies can be marked as "optional" which skips the check if the dependency is missing
4. logs at the "error" level are visible to players, all others are not. A summary is displayed to the player (who may be less technical) and an explanation is dropped in debug.txt.
5. I did try to do this with sending chat messages instead of logs and it didn't work so well; I think the players dont exist while the server is loading or something (which kinda makes sense). Given the desire to halt a server from starting up, I moved on.

2022-12-11 07:18 UTC, Awkanimus commented
Testing notes:
1. Tested world with and without ethereal loaded and ensured world loaded.
2. Tested in world with recent ethereal loaded and ensured world loaded.
3. Changed the required version by adding "99" to the front and validated that error message was provided
4. Changed optional to false and revalidated point 3
5. Changed optional to false and loaded world without ethereal and ensured error (even though this case should have used mod.conf)

2022-12-11 20:02 UTC, Awkanimus commented
For clarity, coding and testing is all done. Not sure if requesting a rereview is the way forward here but that's what I did

2022-12-12 00:51 UTC, wsor4035 commented
im sorry, but these latest commits are absolutely ridiculous. nothing more was needed besides  a minimally modified version of the code listed in https://github.com/mt-mods/moretrees/issues/22#issuecomment-1345102761 - additionally, it seems like luacheck wasnt even used here (see failed ci)

2022-12-12 02:37 UTC, Awkanimus commented
I just noticed you folks use tabs, not spaces. Just a moment.

2022-12-12 02:46 UTC, Awkanimus commented
Ok @wsor4035, a version more similar to the one in the other conversation is force-pushed. Tabs, not spaces are used as thats what the code around it mostly uses. Luacheck (assuming luacheck's config plus the .luacheckrc settings are enough) passes.

2022-12-12 02:53 UTC, wsor4035 approved these changes
couple of minor things, feel free to reject them or change them if you wish. overall this looks good.

use `minetest.global_exists(name)` or `rawget` rather than just `if ethereal then` since minetest has a builtin version of luacheck which is terrible (actual luacheck doesnt complain rightfully so) because it will think your trying to access an undeclared global (when ethereal isnt installed).
doc: https://github.com/minetest/minetest/blob/981d79157a64468d19f140f5c55d8ccd3855fa71/doc/lua_api.txt#L6573-L6574

the comment `-- Validate that if ethereal exists, that it's version is greater than 20220424` could be changed to mention something like `-- Validate that if ethereal exists, that it's version is greater than 20220424 so it doesnt break this mod` giving a why for the check

2022-12-12 02:55 UTC, wsor4035 commented
oh, just noticed `moretress` should be `moretrees` in the `error` function

2022-12-12 05:04 UTC, Awkanimus commented
Ok. The comment is more descriptive, now uses `minetest.global_exists("ethereal")` and s/moretress/moretrees/g.

2022-12-12 05:07 UTC, Awkanimus commented
Also, manual tests with and without ethereal and with a bad version number rerun and continue to pass. Luacheck passes.

2022-12-12 05:16 UTC, wsor4035 commented
looks good. approval still stands.

2022-12-12 05:26 UTC, merged

2022-12-12 05:27 UTC, wsor4035 commented
thank you for your contribution and testing @Awkanimus

2022-12-12 11:23 UTC, Awkanimus commented
Happy to help. Thanks for the timely responses and constructive feedback.